#change port
server:
  port: 8085

spring:
  #mvc view
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  #devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  #oracle settings
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://database-2.ctyqq6wis0lj.ap-northeast-2.rds.amazonaws.com:3306/practiceDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: admin
      password: cjfals62


#mybatis settings
mybatis:
  mapper-locations: classpath:/sqlmapper/*.xml
  configuration:
    map-underscore-to-camel-case: true